/// PC104App.c is the application level file for the Linux PC104 master example
/// which interfaces an PMD PC104 Prodigy board.
/// This based on the ISA interface.  It compiles but not HW available to test it.
/// It runs on a Raspberry Pi and until the call to inw() which causes a segmentation fault.
/// The Raspberry Pi has no PC104 bus so Ivalid memory access?
/// TLK 12/21/2021
/// 
#define PMD_PARALLEL_INTERFACE

#include <stdio.h>
#include "C-Motion.h"
#include "PMDdiag.h"
#include "PMDutil.h"
#include "PMDpar.h"

void main()
{
	PMDuint16 generation, motorType, numberAxes, chip_count, custom, major, minor;
	PMDAxisHandle hAxis1,hAxis2; 
	PMDresult result;
	PMDuint16 status;

	//create handle to axis1 and open 
	result=PMDSetupAxisInterface_Parallel( &hAxis1, PMDAxis1, 0 );
    if(result)
	{
		printf("Error:Could not open PC104 port code=%x\n",result);
		return;
	}
		
	// Create handle to axis2.
	PMDCopyAxisInterface(&hAxis2,&hAxis1,PMDAxis2);
   	
   	result=PMDGetVersion( &hAxis1, &generation, &motorType, &numberAxes, &chip_count, &custom, &major, &minor );
    if(result)
	{
		printf("result=%x\n",result);
		return;
	}
	else
	{	
		printf("PMD Motion Processor MC%d%d%d%d0 v%d.%d\n\n", generation, motorType, numberAxes, chip_count, major, minor);

	}
	
	// To Do:
	// Add any initialization commands like SetupAxis1() generated by Pro-Motion.
	// Then start a move by call ProfileMove() 

   	return;

}

