/// PMDApp.c is the application level file for the RaspberryPi / Linux serial example.
/// However there is nothing Linux specific in this file.  That is in PMDRaspianSer.c
/// This was tested on a Raspberry Pi 3 B+.
/// Hint: Raspberry Pi user's must disable serial debug messages first (raspi-config)
/// TLK 8/24/2021

#define PMD_W32SERIAL_INTERFACE


#include <stdio.h>
#include "C-Motion.h"
#include "PMDutil.h"
#include "PMDdiag.h"

void main()
{
	PMDuint16 generation, motorType, numberAxes, chip_count, custom, major, minor;
	PMDAxisHandle hAxis1; 
	PMDresult result;

	result=PMDSetupAxisInterface_Serial( &hAxis1, PMDAxis1, 0 );
	if(result)
	{
		printf("Error:Could not open serial port code=%x\n",result);
		return;
	}	
	
	PMDSerial_Sync(&hAxis1);
   
   	result=PMDGetVersion( &hAxis1, &generation, &motorType, &numberAxes, &chip_count, &custom, &major, &minor );
    if(result)
	{
		printf("result=%x\n",result);
		return;
	}
	else
	{	
	printf("PMD Motion Processor MC%d%d%d%d0 v%d.%d\n\n", generation, motorType, numberAxes, chip_count, major, minor);

	}
	
	// To Do:
	// Add any initialization commands like SetupAxis1() generated by Pro-Motion.
	// Then start a move by call ProfileMove() 

   	return;

}

